kind: Deployment
apiVersion: apps/v1
metadata:
  name: npm-proxy-cache-deployment
spec:
  replicas: 1
  selector:
   matchLabels:
     app: npm-proxy-cache
  template:
    metadata:
      labels:
        app: npm-proxy-cache
    spec:
      containers:
      - name: npm-proxy-cache-container
        image: trion/npm-proxy-cache
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
kind: Service
apiVersion: v1
metadata:
  name: npm-proxy-cache-service
spec:
  type: ClusterIP
  selector:
    app: npm-proxy-cache
  ports:
    - name: 'http'
      protocol: 'TCP'
      port: 80
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: npm-proxy-cache-np
spec:
  type: NodePort
  selector:
    app: npm-proxy-cache
  ports:
    - name: 'http'
      protocol: 'TCP'
      port: 80
      targetPort: 8080
      nodePort: 31808
